<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Mekumiao.SuCaiFlow.EntityFrameworkCore</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuCaiFlow.Abstractions\SuCaiFlow.Abstractions.csproj" />
    <ProjectReference Include="..\SuCaiFlow.Engine\SuCaiFlow.Engine.csproj" />
    <ProjectReference Include="..\SuCaiFlow.EntityFrameworkCore.Models\SuCaiFlow.EntityFrameworkCore.Models.csproj" />
  </ItemGroup>

</Project>
