<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Mekumiao.SuCaiFlow.Engine" Version="1.1.0" />
    <PackageVersion Include="Mekumiao.SuCaiFlow.EntityFrameworkCore" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.61.0" />
  </ItemGroup>
</Project>