// <auto-generated />
using SuCaiFlow.Contracts.Entities;
using SuCaiFlow.Contracts.Interfaces;

namespace SuCaiFlow.Core.Services
{
    /// <summary>
    /// 站点采集器基类，提供通用的采集功能实现
    /// </summary>
    public abstract class BaseSiteCollector : ISiteCollector
    {
        public abstract string SiteIdentifier { get; }
        public abstract string DisplayName { get; }
        
        public virtual bool CanHandle(string url)
        {
            // 默认实现：检查URL是否包含站点标识符
            return url.Contains(SiteIdentifier, StringComparison.OrdinalIgnoreCase);
        }

        public abstract Task<List<string>> ParsePageAsync(CollectionTask task, string pageUrl, CollectionTaskConfig? config = null);

        public virtual string ConstructNextPageUrlByPattern(string baseUrl, int pageNumber, string pattern)
        {
            // 根据模式替换页码
            var result = pattern.Replace("{pageNumber}", pageNumber.ToString());
            return result;
        }

        public virtual string ConstructNextPageUrl(string baseUrl, int pageNumber)
        {
            // 默认实现：在URL后添加?page=参数
            var separator = baseUrl.Contains('?') ? '&' : '?';
            return string.Format("{0}{1}page={2}", baseUrl, separator, pageNumber);
        }

        public virtual string GetDefaultSelector()
        {
            // 默认实现：返回通用选择器
            return "img[src], a[href]";
        }

        public abstract Task<CollectedAsset?> DownloadAssetAsync(string url, CollectionTaskConfig? config = null);

        public virtual string PreprocessAssetUrl(string url, CollectionTaskConfig? config = null)
        {
            // 默认实现：直接返回URL
            return url;
        }
    }
}
