// <auto-generated />
using Microsoft.Extensions.Logging;
using SuCaiFlow.Contracts.Interfaces;

namespace SuCaiFlow.Core.Services
{
    /// <summary>
    /// 站点采集器管理器实现
    /// </summary>
    public class SiteCollectorManager : ISiteCollectorManager
    {
        private readonly ILogger<SiteCollectorManager> _logger;
        private readonly List<ISiteCollector> _collectors;

        public SiteCollectorManager(ILogger<SiteCollectorManager> logger)
        {
            _logger = logger;
            _collectors = new List<ISiteCollector>();
        }

        public void RegisterCollector(ISiteCollector collector)
        {
            if (_collectors.Any(c => c.SiteIdentifier.Equals(collector.SiteIdentifier, StringComparison.OrdinalIgnoreCase)))
            {
                _logger.LogWarning("采集器 {SiteIdentifier} 已经注册", collector.SiteIdentifier);
                return;
            }

            _collectors.Add(collector);
            _logger.LogInformation("注册了采集器: {SiteIdentifier} ({DisplayName})", collector.SiteIdentifier, collector.DisplayName);
        }

        public ISiteCollector? GetCollectorForUrl(string url)
        {
            var collector = _collectors.FirstOrDefault(c => c.CanHandle(url));
            if (collector != null)
            {
                _logger.LogDebug("为URL {Url} 找到采集器: {SiteIdentifier}", url, collector.SiteIdentifier);
            }
            else
            {
                _logger.LogWarning("未找到可以处理URL {Url} 的采集器", url);
            }
            return collector;
        }

        public List<ISiteCollector> GetAllCollectors()
        {
            return _collectors.ToList();
        }

        public ISiteCollector? GetCollectorByIdentifier(string siteIdentifier)
        {
            var collector = _collectors.FirstOrDefault(c => 
                c.SiteIdentifier.Equals(siteIdentifier, StringComparison.OrdinalIgnoreCase));
            
            if (collector != null)
            {
                _logger.LogDebug("找到采集器: {SiteIdentifier}", siteIdentifier);
            }
            else
            {
                _logger.LogWarning("未找到标识符为 {SiteIdentifier} 的采集器", siteIdentifier);
            }
            
            return collector;
        }
    }
}
