// <auto-generated />
using Microsoft.Extensions.Logging;

using SuCaiFlow.Contracts.Interfaces;

namespace SuCaiFlow.Core.Services
{
    /// <summary>
    /// 任务执行服务实现
    /// </summary>
    public class TaskExecutionService : ITaskExecutionService
    {
        private readonly ILogger<TaskExecutionService> _logger;
        private readonly HashSet<Guid> _runningTasks;

        public TaskExecutionService(ILogger<TaskExecutionService> logger)
        {
            _logger = logger;
            _runningTasks = new HashSet<Guid>();
        }

        public async Task<bool> IsTaskRunningAsync(Guid taskId)
        {
            var isRunning = _runningTasks.Contains(taskId);
            _logger.LogDebug("检查任务 {TaskId} 运行状态: {IsRunning}", taskId, isRunning);
            return isRunning;
        }

        public async Task<bool> MarkTaskAsRunningAsync(Guid taskId)
        {
            if (_runningTasks.Add(taskId))
            {
                _logger.LogInformation("标记任务 {TaskId} 为运行状态", taskId);
                return true;
            }
            _logger.LogWarning("任务 {TaskId} 已在运行状态", taskId);
            return false;
        }

        public async Task<bool> MarkTaskAsCompletedAsync(Guid taskId)
        {
            if (_runningTasks.Remove(taskId))
            {
                _logger.LogInformation("标记任务 {TaskId} 为完成状态", taskId);
                return true;
            }
            _logger.LogWarning("任务 {TaskId} 不在运行状态", taskId);
            return false;
        }

        public async Task<bool> MarkTaskAsFailedAsync(Guid taskId)
        {
            if (_runningTasks.Remove(taskId))
            {
                _logger.LogInformation("标记任务 {TaskId} 为失败状态", taskId);
                return true;
            }
            _logger.LogWarning("任务 {TaskId} 不在运行状态", taskId);
            return false;
        }
    }
}
