// <auto-generated />
using SuCaiFlow.Contracts.Entities;

namespace SuCaiFlow.Contracts.Services
{
    /// <summary>
    /// 任务执行服务接口，用于管理采集任务的执行状态
    /// </summary>
    public interface ITaskExecutionService
    {
        /// <summary>
        /// 检查任务是否正在运行
        /// </summary>
        /// <param name="taskId">任务ID</param>
        /// <returns>如果任务正在运行则返回true，否则返回false</returns>
        Task<bool> IsTaskRunningAsync(Guid taskId);
        
        /// <summary>
        /// 标记任务为正在运行状态
        /// </summary>
        /// <param name="taskId">任务ID</param>
        /// <returns>操作是否成功</returns>
        Task<bool> MarkTaskAsRunningAsync(Guid taskId);
        
        /// <summary>
        /// 标记任务为完成状态
        /// </summary>
        /// <param name="taskId">任务ID</param>
        /// <returns>操作是否成功</returns>
        Task<bool> MarkTaskAsCompletedAsync(Guid taskId);
    }
}
