// <auto-generated />
using SuCaiFlow.Contracts.Entities;

namespace SuCaiFlow.Contracts.Events
{
    /// <summary>
    /// 采集任务开始事件
    /// </summary>
    public class CollectionTaskStartedEvent
    {
        public Guid TaskId { get; set; }
        public string TaskName { get; set; } = string.Empty;
        public string Url { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 采集任务进度更新事件
    /// </summary>
    public class CollectionTaskProgressEvent
    {
        public Guid TaskId { get; set; }
        public int AssetsCollectedCount { get; set; }
        public int TotalAssetsExpected { get; set; }
        public double ProgressPercentage { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 采集任务完成事件
    /// </summary>
    public class CollectionTaskCompletedEvent
    {
        public Guid TaskId { get; set; }
        public string TaskName { get; set; } = string.Empty;
        public int AssetsCollectedCount { get; set; }
        public CollectionTaskStatus Status { get; set; }
        public DateTime CompletedAt { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 采集任务失败事件
    /// </summary>
    public class CollectionTaskFailedEvent
    {
        public Guid TaskId { get; set; }
        public string TaskName { get; set; } = string.Empty;
        public string ErrorMessage { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 资源下载开始事件
    /// </summary>
    public class AssetDownloadStartedEvent
    {
        public Guid TaskId { get; set; }
        public Guid AssetId { get; set; }
        public string AssetUrl { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 资源下载完成事件
    /// </summary>
    public class AssetDownloadCompletedEvent
    {
        public Guid TaskId { get; set; }
        public Guid AssetId { get; set; }
        public string AssetUrl { get; set; } = string.Empty;
        public long? Size { get; set; }
        public string? ContentType { get; set; }
        public bool Success { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 资源下载进度事件
    /// </summary>
    public class AssetDownloadProgressEvent
    {
        public Guid TaskId { get; set; }
        public Guid AssetId { get; set; }
        public string AssetUrl { get; set; } = string.Empty;
        public long BytesDownloaded { get; set; }
        public long? TotalSize { get; set; }
        public double ProgressPercentage { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }
}
