// <auto-generated />
using SuCaiFlow.Contracts.Entities;

namespace SuCaiFlow.Contracts.Events
{
    /// <summary>
    /// 采集任务开始事件
    /// </summary>
    public class CollectionTaskStartedEvent
    {
        public Guid TaskId { get; set; }
        public string TaskName { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 采集任务完成事件
    /// </summary>
    public class CollectionTaskCompletedEvent
    {
        public Guid TaskId { get; set; }
        public string TaskName { get; set; } = string.Empty;
        public int AssetsCollected { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 采集任务失败事件
    /// </summary>
    public class CollectionTaskFailedEvent
    {
        public Guid TaskId { get; set; }
        public string TaskName { get; set; } = string.Empty;
        public string ErrorMessage { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 资源采集开始事件
    /// </summary>
    public class AssetCollectionStartedEvent
    {
        public Guid TaskId { get; set; }
        public Guid AssetId { get; set; }
        public string AssetUrl { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 资源采集完成事件
    /// </summary>
    public class AssetCollectionCompletedEvent
    {
        public Guid TaskId { get; set; }
        public Guid AssetId { get; set; }
        public string AssetUrl { get; set; } = string.Empty;
        public string LocalPath { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// 资源采集失败事件
    /// </summary>
    public class AssetCollectionFailedEvent
    {
        public Guid TaskId { get; set; }
        public Guid AssetId { get; set; }
        public string AssetUrl { get; set; } = string.Empty;
        public string ErrorMessage { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }
}
