<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Mekumiao.SuCaiFlow.EntityFrameworkCore.Models</PackageId>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Relational entities for the SuCaiFlow Entity Framework Core stores.</Description>
    <PackageTags>$(PackageTags);entityframeworkcore;models</PackageTags>
  </PropertyGroup>

</Project>
