<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SuCaiFlow.Engine\SuCaiFlow.Engine.csproj" />
    <ProjectReference Include="..\..\src\SuCaiFlow.EntityFrameworkCore\SuCaiFlow.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
